language: php

sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fash_finish: true
  include:
    - php: 7.0

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - vendor/bin/phpcs -p --standart=PSR2 --extensions=php ./src
