language: php

sudo: false

php:
  - 7.0

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - mysql -u root -e 'CREATE DATABASE symfony CHARSET utf8;'

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php bin/console doctrine:schema:create

script:
  - vendor/bin/phpcs -p --standard=PSR2 --extensions=php ./src

notifications:
  email: false
  slack: nfqakademija:OdtQKvlAgV1zO3B1ia3Vbiac
