# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value


services:
    app.activity:
          class: AppBundle\Service\ActivityService
          arguments: ["@doctrine.orm.entity_manager"]
    app.result:
          class: AppBundle\Service\ResultService
          arguments: ["@doctrine.orm.entity_manager"]
    app.lesson_service:
        class: AppBundle\Service\LessonService
        arguments: [ "@doctrine.orm.entity_manager" ]

    my_user_provider:
        class: AppBundle\Security\Core\User\FOSUBUserProvider
        #facebook: facebook_id, this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ["@fos_user.user_manager",{ google: google_id}]

    app.menu_listener:
        class: AppBundle\EventListener\MenuItemListener
        tags:
          - { name: kernel.event_listener, event:theme.sidebar_setup_menu, method:onSetupMenu }
