# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:


services:

  app.menu_listener:
    class: AppBundle\EventListener\MenuItemListener
    tags:
      - { name: kernel.event_listener, event:theme.sidebar_setup_menu, method:onSetupMenu }
