# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value


services:
    app.activity:
          class: AppBundle\Service\ActivityService
          arguments: ["@doctrine.orm.entity_manager"]
    app.result:
          class: AppBundle\Service\ResultService
          arguments: ["@doctrine.orm.entity_manager"]
    app.lesson_service:
        class: AppBundle\Service\LessonService
        arguments: ['@app.lesson_repository']

    app.lesson_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\Lesson

    app.lesson_listener:
        class: AppBundle\EventListener\LessonControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onInit }

    app.menu_listener:
        class: AppBundle\EventListener\MenuItemListener
        tags:
          - { name: kernel.event_listener, event: theme.sidebar_setup_menu, method: onSetupMenu }
